"""
ПОЛИТИКИ: 44 бойца со статами, приёмами-мемами и описанием.
Каждый боец — dict. Используется engine.py и server.py.
"""

from __future__ import annotations

FIGHTERS: list[dict] = [
    # ───────────── CURRENT / RECENT ─────────────
    {
        "id": "trump",
        "name": "Дональд Трумп",
        "name_en": "Donald Troomp",
        "country": "🇺🇸",
        "era": "current",
        "type": "Берсерк",
        "bio": "Бизнесмен, шоумен, 45-й и 47-й президент США. Непредсказуем, как мартовский твит.",
        "taunt": "You're fired!",
        "hp": 220, "atk": 38, "def": 18, "spd": 5, "luck": 9,
        "weakness": "Дипломатия",
        "strength": "Медиа-хаос",
        "strength_meme": "Один твит — и биржа в огне 📉🔥",
        "weakness_meme": "Дипломатия? Это которая с бантиком? 🎀",
        "color": "#e74c3c",
        "gradient": "linear-gradient(135deg, #c0392b, #e74c3c, #f39c12)",
        "emoji": "🍊",
        "moves": [
            {"name": "COVFEFE", "type": "light", "base_dmg": 14, "accuracy": 92, "desc": "Заклинание из твита. Никто не знает что это, но больно"},
            {"name": "Тут есть нефть?", "type": "heavy", "base_dmg": 36, "accuracy": 58, "desc": "Нюхает воздух, находит нефть, вторгается. Демократия доставлена."},
            {"name": "Стеночка", "type": "special", "base_dmg": 24, "accuracy": 72, "desc": "Кидает стену. Мексика оплатит лечение. И ремонт.", "effect": "def_down"},
            {"name": "Украсть президента", "type": "ultimate", "base_dmg": 55, "accuracy": 65, "desc": "Пересчёт голосов! Нашёл 11780! Враг больше не президент.", "cooldown": 3},
        ],
    },
    {
        "id": "putin",
        "name": "Владимир Путен",
        "name_en": "Vladimir Pooten",
        "country": "🇷🇺",
        "era": "current",
        "type": "Контроль",
        "bio": "Мастер дзюдо и геополитики. Спокоен, расчётлив, опасен.",
        "taunt": "Мочить в сортире.",
        "hp": 260, "atk": 30, "def": 35, "spd": 6, "luck": 7,
        "weakness": "Экономическое давление",
        "strength": "Стратегия",
        "strength_meme": "Играет в 5D-шахматы, пока все в шашки 🧠♟️",
        "weakness_meme": "Санкции бьют больнее дзюдо 💸",
        "color": "#3498db",
        "gradient": "linear-gradient(135deg, #1a5276, #2980b9, #5dade2)",
        "emoji": "🐻",
        "moves": [
            {"name": "Длинный стол", "type": "light", "base_dmg": 13, "accuracy": 90, "desc": "15-метровый стол летит в лицо. Социальная дистанция."},
            {"name": "Голый торс", "type": "heavy", "base_dmg": 35, "accuracy": 55, "desc": "Снимает рубашку верхом на медведе. Критический урон."},
            {"name": "Мочить в сортире", "type": "special", "base_dmg": 20, "accuracy": 80, "desc": "Враг загнан в туалет. Выхода нет.", "effect": "def_down"},
            {"name": "Опоздание на 4 часа", "type": "ultimate", "base_dmg": 58, "accuracy": 60, "desc": "Враг ждал 4 часа и умер от нервов", "cooldown": 3},
        ],
    },
    {
        "id": "biden",
        "name": "Джо Байдон",
        "name_en": "Joe Baidon",
        "country": "🇺🇸",
        "era": "current",
        "type": "Танк",
        "bio": "46-й президент США. Медленный, но упорный. Опыт — его бро.",
        "taunt": "C'mon man!",
        "hp": 280, "atk": 18, "def": 32, "spd": 2, "luck": 5,
        "weakness": "Скорость",
        "strength": "Выносливость",
        "strength_meme": "Как танк — медленный, но прёт 🐢💪",
        "weakness_meme": "Спит на совещаниях стоя 😴",
        "color": "#2c3e50",
        "gradient": "linear-gradient(135deg, #2c3e50, #3498db, #ecf0f1)",
        "emoji": "🍦",
        "moves": [
            {"name": "Падение с велика", "type": "light", "base_dmg": 11, "accuracy": 85, "desc": "Падает с велосипеда — НА врага. Гений."},
            {"name": "Битва с лестницей", "type": "heavy", "base_dmg": 28, "accuracy": 62, "desc": "Спотыкается на трапе 3 раза. Каждый раз по врагу."},
            {"name": "Забыл имя", "type": "special", "base_dmg": 18, "accuracy": 70, "desc": "Называет врага именем его бывшей. Психоурон.", "effect": "confuse"},
            {"name": "Dark Brandon", "type": "ultimate", "base_dmg": 50, "accuracy": 68, "desc": "Глаза загораются лазерами. Мороженое тает.", "cooldown": 3},
        ],
    },
    {
        "id": "xi",
        "name": "Си Цзиньпан",
        "name_en": "Xi Jinpang",
        "country": "🇨🇳",
        "era": "current",
        "type": "Контроль",
        "bio": "Лидер 1.4 миллиарда. Терпеливый стратег с бесконечными ресурсами.",
        "taunt": "Общее процветание для всех.",
        "hp": 250, "atk": 28, "def": 30, "spd": 4, "luck": 6,
        "weakness": "Гибкость",
        "strength": "Ресурсы",
        "strength_meme": "1.4 миллиарда человек не могут ошибаться... или могут? 🇨🇳",
        "weakness_meme": "Гибкость? Только тайчи по утрам 🧘",
        "color": "#c0392b",
        "gradient": "linear-gradient(135deg, #922b21, #c0392b, #e74c3c)",
        "emoji": "🐉",
        "moves": [
            {"name": "Бан Винни-Пуха", "type": "light", "base_dmg": 12, "accuracy": 90, "desc": "Банит всё, что похоже на медведя. Включая врага."},
            {"name": "Великий файрвол", "type": "heavy", "base_dmg": 30, "accuracy": 60, "desc": "Враг отключён от интернета навсегда"},
            {"name": "Социальный рейтинг −999", "type": "special", "base_dmg": 20, "accuracy": 78, "desc": "Рейтинг врага падает. Ему нельзя даже в автобус.", "effect": "atk_down"},
            {"name": "Армия Терракоты", "type": "ultimate", "base_dmg": 52, "accuracy": 64, "desc": "8000 глиняных воинов + 1.4 млрд живых", "cooldown": 3},
        ],
    },
    {
        "id": "kim",
        "name": "Ким Чен Ыш",
        "name_en": "Kim Jong-ush",
        "country": "🇰🇵",
        "era": "current",
        "type": "Берсерк",
        "bio": "Верховный лидер КНДР. Непредсказуемый, непробиваемый, с ракетами.",
        "taunt": "Огненный шторм возмездия!",
        "hp": 200, "atk": 42, "def": 15, "spd": 3, "luck": 8,
        "weakness": "Экономика",
        "strength": "Ядерная угроза",
        "strength_meme": "Красная кнопка всегда при себе ☢️",
        "weakness_meme": "Экономика на уровне Minecraft 💎⛏️",
        "color": "#1abc9c",
        "gradient": "linear-gradient(135deg, #0e6655, #1abc9c, #76d7c4)",
        "emoji": "🚀",
        "moves": [
            {"name": "Стрижка Верховного", "type": "light", "base_dmg": 15, "accuracy": 85, "desc": "Причёска настолько мощная, что наносит психоурон"},
            {"name": "Ракета в море", "type": "heavy", "base_dmg": 38, "accuracy": 50, "desc": "Запустил ракету. Куда попала — военная тайна (в море)"},
            {"name": "Гигантский бинокль", "type": "special", "base_dmg": 18, "accuracy": 82, "desc": "Смотрит в бинокль размером с телескоп. Видит слабости.", "effect": "def_down"},
            {"name": "Фейковые слёзы", "type": "ultimate", "base_dmg": 55, "accuracy": 58, "desc": "Рыдает так убедительно, что враг сдаётся от жалости", "cooldown": 3},
        ],
    },
    {
        "id": "zelensky",
        "name": "Владимир Зелинский",
        "name_en": "Volodymyr Zelinskiy",
        "country": "🇺🇦",
        "era": "current",
        "type": "Бруйзер",
        "bio": "Из комика в военного президента. Харизма и стойкость.",
        "taunt": "Мне нужны боеприпасы, а не эвакуация.",
        "hp": 230, "atk": 32, "def": 25, "spd": 7, "luck": 8,
        "weakness": "Ресурсы",
        "strength": "Харизма",
        "strength_meme": "Квартал 95 → президент. Импровизация бога 🎭",
        "weakness_meme": "Ресурсы? Какие ресурсы? 🤷",
        "color": "#f1c40f",
        "gradient": "linear-gradient(135deg, #2e86c1, #f1c40f, #2e86c1)",
        "emoji": "🌻",
        "moves": [
            {"name": "Пианино из КВН", "type": "light", "base_dmg": 14, "accuracy": 90, "desc": "Играет на пианино. Тем самым местом. Враг в шоке."},
            {"name": "Зелёная футболка", "type": "heavy", "base_dmg": 34, "accuracy": 62, "desc": "Футболка заряжена энергией 100 пресс-конференций"},
            {"name": "Мне нужны патроны!", "type": "special", "base_dmg": 22, "accuracy": 76, "desc": "Отказ от эвакуации даёт +500 к морали", "effect": "atk_up"},
            {"name": "Слуга народа", "type": "ultimate", "base_dmg": 48, "accuracy": 72, "desc": "Из комика в военного лидера. Весь народ за спиной.", "cooldown": 3},
        ],
    },
    {
        "id": "macron",
        "name": "Эммануэль Макрун",
        "name_en": "Emmanuel Macroon",
        "country": "🇫🇷",
        "era": "current",
        "type": "Ассасин",
        "bio": "Юный, дерзкий, элегантный. Бьёт пощёчины и реформы.",
        "taunt": "La République, c'est moi!",
        "hp": 190, "atk": 35, "def": 20, "spd": 8, "luck": 7,
        "weakness": "Протесты",
        "strength": "Элегантность",
        "strength_meme": "Элегантно уничтожает. В Dior. 👔✨",
        "weakness_meme": "Жёлтые жилеты — его криптонит 🟡",
        "color": "#8e44ad",
        "gradient": "linear-gradient(135deg, #002395, #ffffff, #ed2939)",
        "emoji": "🥐",
        "moves": [
            {"name": "Пощёчина (входящая)", "type": "light", "base_dmg": 15, "accuracy": 92, "desc": "Получает пощёчину → отражает её ×10"},
            {"name": "Жёлтые жилеты", "type": "heavy", "base_dmg": 30, "accuracy": 56, "desc": "Вызывает протест. Горит всё. Включая врага."},
            {"name": "Jupiter Mode", "type": "special", "base_dmg": 24, "accuracy": 74, "desc": "Объявляет себя Юпитером. Молнии прилагаются.", "effect": "spd_up"},
            {"name": "Force de Baguette", "type": "ultimate", "base_dmg": 52, "accuracy": 66, "desc": "Ядерный багет. 290 боеголовок внутри хрустящей корочки.", "cooldown": 3},
        ],
    },
    {
        "id": "boris",
        "name": "Борис Джонсан",
        "name_en": "Boris Johnsan",
        "country": "🇬🇧",
        "era": "current",
        "type": "Берсерк",
        "bio": "Хаотичный блондин. Никогда не знаешь, что он сделает.",
        "taunt": "Get Brexit Done!",
        "hp": 210, "atk": 30, "def": 16, "spd": 5, "luck": 10,
        "weakness": "Дисциплина",
        "strength": "Хаос",
        "strength_meme": "Хаос — это лестница, а он наверху 🪜💥",
        "weakness_meme": "Причёска — единственная стратегия 💇",
        "color": "#f39c12",
        "gradient": "linear-gradient(135deg, #d4ac0d, #f39c12, #f5b041)",
        "emoji": "🦁",
        "moves": [
            {"name": "Удар причёской", "type": "light", "base_dmg": 13, "accuracy": 88, "desc": "Волосы живут своей жизнью и атакуют"},
            {"name": "Застрял на зиплайне", "type": "heavy", "base_dmg": 32, "accuracy": 55, "desc": "Висит на тросе с флагами. Падает на врага."},
            {"name": "Partygate", "type": "special", "base_dmg": 20, "accuracy": 80, "desc": "Устраивает вечеринку во время локдауна. Все в шоке.", "effect": "confuse"},
            {"name": "Автобус Brexit", "type": "ultimate", "base_dmg": 48, "accuracy": 70, "desc": "350 млн фунтов в неделю — на лбу у врага", "cooldown": 3},
        ],
    },
    {
        "id": "merkel",
        "name": "Ангела Мёркель",
        "name_en": "Angela Mirkel",
        "country": "🇩🇪",
        "era": "current",
        "type": "Танк",
        "bio": "16 лет у власти. Тихая, системная, несокрушимая.",
        "taunt": "Wir schaffen das.",
        "hp": 300, "atk": 20, "def": 38, "spd": 3, "luck": 6,
        "weakness": "Скорость",
        "strength": "Выдержка",
        "strength_meme": "Терпит как скала. 16 лет терпит 🪨",
        "weakness_meme": "Ускориться? Пиво ещё не допито 🍺",
        "color": "#5d6d7e",
        "gradient": "linear-gradient(135deg, #2c3e50, #5d6d7e, #aeb6bf)",
        "emoji": "🔷",
        "moves": [
            {"name": "Ромб Меркель", "type": "light", "base_dmg": 10, "accuracy": 95, "desc": "Складывает руки ромбом. Защитное поле. Скучно но больно."},
            {"name": "16 лет у власти", "type": "heavy", "base_dmg": 28, "accuracy": 65, "desc": "Просто пересидела всех. И тебя пересидит."},
            {"name": "Тихая дипломатия", "type": "special", "base_dmg": 18, "accuracy": 82, "desc": "Незаметно меняет расклад. Враг не понял что случилось.", "effect": "def_up"},
            {"name": "Ordnung muss sein", "type": "ultimate", "base_dmg": 45, "accuracy": 75, "desc": "Немецкий порядок. Системное, скучное, неотвратимое уничтожение.", "cooldown": 3},
        ],
    },
    {
        "id": "modi",
        "name": "Нарендра Моби",
        "name_en": "Narendra Mobi",
        "country": "🇮🇳",
        "era": "current",
        "type": "Саппорт",
        "bio": "Лидер 1.4 миллиарда. Йога-мастер с железной волей.",
        "taunt": "Jai Hind!",
        "hp": 240, "atk": 25, "def": 28, "spd": 5, "luck": 7,
        "weakness": "Прямая атака",
        "strength": "Масса людей",
        "strength_meme": "Миллиард фанатов — лучшая броня 🛡️",
        "weakness_meme": "В ближнем бою — только йога 🧘‍♂️",
        "color": "#e67e22",
        "gradient": "linear-gradient(135deg, #e67e22, #f39c12, #138808)",
        "emoji": "🪷",
        "moves": [
            {"name": "Поза кобры", "type": "light", "base_dmg": 12, "accuracy": 90, "desc": "Йога-приём: изгибается так, что враг ломает глаза"},
            {"name": "Селфи-цунами", "type": "heavy", "base_dmg": 30, "accuracy": 58, "desc": "1.4 млрд людей делают селфи. Вспышки ослепляют."},
            {"name": "Чайная дипломатия", "type": "special", "base_dmg": 20, "accuracy": 78, "desc": "Угощает чаем. Чай с перцем. Изнутри.", "effect": "spd_down"},
            {"name": "Брахмастра", "type": "ultimate", "base_dmg": 50, "accuracy": 65, "desc": "Древнее оружие богов + миллиард для масштаба", "cooldown": 3},
        ],
    },
    {
        "id": "erdogan",
        "name": "Реджеп Эрдуган",
        "name_en": "Recep Erdugan",
        "country": "🇹🇷",
        "era": "current",
        "type": "Бруйзер",
        "bio": "Султан XXI века. Играет на всех досках одновременно.",
        "taunt": "Один народ, одно государство, один лидер!",
        "hp": 240, "atk": 33, "def": 24, "spd": 5, "luck": 7,
        "weakness": "Экономика (инфляция)",
        "strength": "Многоходовка",
        "strength_meme": "Многоходовочка. Все в шоке 🎩🐇",
        "weakness_meme": "Инфляция 80%. Лира плачет 📉😭",
        "color": "#c0392b",
        "gradient": "linear-gradient(135deg, #c0392b, #e74c3c, #f5b7b1)",
        "emoji": "🌙",
        "moves": [
            {"name": "Bayraktar", "type": "light", "base_dmg": 15, "accuracy": 88, "desc": "TB2 вылетает под песню. Песня застревает в голове."},
            {"name": "Удар арбузом", "type": "heavy", "base_dmg": 33, "accuracy": 58, "desc": "Кто-то назвал его продавцом арбузов. Арбуз теперь оружие."},
            {"name": "Султан-мод", "type": "special", "base_dmg": 22, "accuracy": 75, "desc": "Косплеит Сулеймана. Дворец за 600 млн прилагается.", "effect": "atk_up"},
            {"name": "Котопокалипсис", "type": "ultimate", "base_dmg": 50, "accuracy": 64, "desc": "Армия стамбульских котов. Царапают насмерть.", "cooldown": 3},
        ],
    },
    {
        "id": "netanyahu",
        "name": "Биньямин Нетаньяхо",
        "name_en": "Benjamin Netanyaho",
        "country": "🇮🇱",
        "era": "current",
        "type": "Ассасин",
        "bio": "Биби. Мастер выживания. Политический кот с 9 жизнями.",
        "taunt": "Israel will defend itself. By itself.",
        "hp": 200, "atk": 38, "def": 22, "spd": 7, "luck": 9,
        "weakness": "Суды",
        "strength": "Разведка",
        "strength_meme": "Моссад не спит. Никогда 🕶️",
        "weakness_meme": "Судьи — его финальный босс ⚖️",
        "color": "#2e86c1",
        "gradient": "linear-gradient(135deg, #1b4f72, #2e86c1, #aed6f1)",
        "emoji": "✡️",
        "moves": [
            {"name": "9 жизней Биби", "type": "light", "base_dmg": 12, "accuracy": 94, "desc": "Политический кот. Убить невозможно. Промахнуться тоже."},
            {"name": "Пейджер-бум", "type": "heavy", "base_dmg": 36, "accuracy": 60, "desc": "Все пейджеры врага взрываются. Одновременно."},
            {"name": "Судебный иммунитет", "type": "special", "base_dmg": 24, "accuracy": 76, "desc": "12 дел в суде. Ни одно не попало. Враг в шоке.", "effect": "def_down"},
            {"name": "Samson Option", "type": "ultimate", "base_dmg": 58, "accuracy": 58, "desc": "Если я падаю — падают ВСЕ. Ветхозаветный финиш.", "cooldown": 3},
        ],
    },
    {
        "id": "milei",
        "name": "Хавьер Милай",
        "name_en": "Javier Milay",
        "country": "🇦🇷",
        "era": "current",
        "type": "Берсерк",
        "bio": "Либертарианский безумец с бензопилой. Рубит всё.",
        "taunt": "¡VIVA LA LIBERTAD, CARAJO!",
        "hp": 190, "atk": 40, "def": 12, "spd": 8, "luck": 8,
        "weakness": "Оборона",
        "strength": "Агрессия",
        "strength_meme": "БЕНЗОПИЛА В ПАРЛАМЕНТЕ! АААА! 🪚",
        "weakness_meme": "Обороняться? Это для слабых! 🫠",
        "color": "#7d3c98",
        "gradient": "linear-gradient(135deg, #4a235a, #7d3c98, #d2b4de)",
        "emoji": "🪚",
        "moves": [
            {"name": "ЛИБЕРТАААД!!!", "type": "light", "base_dmg": 16, "accuracy": 86, "desc": "Орёт так, что у врага лопаются стёкла и барабанные"},
            {"name": "Бензопила хаоса", "type": "heavy", "base_dmg": 34, "accuracy": 55, "desc": "ВЖЖЖЖ! Рубит бюджет, министерства и головы"},
            {"name": "Клоны-мастифы", "type": "special", "base_dmg": 22, "accuracy": 78, "desc": "4 клонированных пса. Каждый назван в честь экономиста.", "effect": "atk_up"},
            {"name": "Парик Бесконечности", "type": "ultimate", "base_dmg": 55, "accuracy": 60, "desc": "Снимает парик. Под ним ещё один. И ещё. Вихрь париков.", "cooldown": 3},
        ],
    },
    {
        "id": "lukashenko",
        "name": "Александр Лукошенко",
        "name_en": "Alexander Lukoshenko",
        "country": "🇧🇾",
        "era": "current",
        "type": "Танк",
        "bio": "Последний диктатор Европы. Бульба, хоккей, усы.",
        "taunt": "Я вам покажу, что такое диктатура!",
        "hp": 270, "atk": 22, "def": 34, "spd": 3, "luck": 6,
        "weakness": "Изоляция",
        "strength": "Стойкость",
        "strength_meme": "Последний диктатор Европы и горд 🏆",
        "weakness_meme": "Изоляция? Зато картошка своя 🥔",
        "color": "#27ae60",
        "gradient": "linear-gradient(135deg, #1e8449, #27ae60, #82e0aa)",
        "emoji": "🥔",
        "moves": [
            {"name": "Картошка-снаряд", "type": "light", "base_dmg": 12, "accuracy": 93, "desc": "Бульба не промахивается. Никогда. Белорусская точность."},
            {"name": "Батька на тракторе", "type": "heavy", "base_dmg": 30, "accuracy": 62, "desc": "МТЗ-82 едет на врага. Батька за рулём. В шортах."},
            {"name": "Тараканий бег", "type": "special", "base_dmg": 18, "accuracy": 84, "desc": "Тысячи тараканов. Враг визжит и теряет концентрацию.", "effect": "confuse"},
            {"name": "Я вам покажу диктатуру!", "type": "ultimate", "base_dmg": 46, "accuracy": 70, "desc": "Показал. Всем. С автоматом и в бронежилете.", "cooldown": 3},
        ],
    },
    {
        "id": "trudeau",
        "name": "Джастин Трюбо",
        "name_en": "Justin Trubo",
        "country": "🇨🇦",
        "era": "current",
        "type": "Саппорт",
        "bio": "Красивый, добрый, извиняющийся. Но есть кленовый сироп.",
        "taunt": "I apologize... but I'll still win.",
        "hp": 220, "atk": 22, "def": 26, "spd": 6, "luck": 7,
        "weakness": "Жёсткость",
        "strength": "Обаяние",
        "strength_meme": "Обаяшка уровня Disney Prince 🫅✨",
        "weakness_meme": "Жёсткость уровня пуховой подушки 🪶",
        "color": "#e74c3c",
        "gradient": "linear-gradient(135deg, #c0392b, #ecf0f1, #c0392b)",
        "emoji": "🍁",
        "moves": [
            {"name": "Извини-удар", "type": "light", "base_dmg": 10, "accuracy": 95, "desc": "Бьёт и сразу извиняется. Sorry! *бьёт* Sorry!"},
            {"name": "Бровь-бумеранг", "type": "heavy", "base_dmg": 28, "accuracy": 60, "desc": "Бровь отклеивается, летит, возвращается. Как в том видео."},
            {"name": "Атака носками", "type": "special", "base_dmg": 18, "accuracy": 82, "desc": "Дизайнерские носки. На каждом — боевой рисунок.", "effect": "confuse"},
            {"name": "Канадская вежливость", "type": "ultimate", "base_dmg": 42, "accuracy": 75, "desc": "Так вежлив, что враг сдаётся от стыда за своё поведение", "cooldown": 3},
        ],
    },
    # ───────────── HISTORICAL ─────────────
    {
        "id": "churchill",
        "name": "Уинстон Черчулль",
        "name_en": "Winston Churchull",
        "country": "🇬🇧",
        "era": "historical",
        "type": "Танк",
        "bio": "Бульдог. Никогда не сдаётся. Виски и сигара.",
        "taunt": "We shall never surrender!",
        "hp": 280, "atk": 26, "def": 32, "spd": 3, "luck": 8,
        "weakness": "Скорость",
        "strength": "Мораль",
        "strength_meme": "Речи, от которых враг сдаётся сам 🎤",
        "weakness_meme": "Быстрый? Только с бокалом виски 🥃",
        "color": "#1a5276",
        "gradient": "linear-gradient(135deg, #1a5276, #2c3e50, #85929e)",
        "emoji": "🎩",
        "moves": [
            {"name": "Виски-сплэш", "type": "light", "base_dmg": 12, "accuracy": 88, "desc": "Плещет виски в лицо. В руке осталась сигара для добивания."},
            {"name": "Пьяный бульдог", "type": "heavy", "base_dmg": 30, "accuracy": 60, "desc": "Пьян, но не сдаётся. Никогда. НИКОГДА."},
            {"name": "V-знак наоборот", "type": "special", "base_dmg": 20, "accuracy": 80, "desc": "Показывает V задом наперёд. Британское оскорбление.", "effect": "atk_down"},
            {"name": "Never Surrender", "type": "ultimate", "base_dmg": 50, "accuracy": 68, "desc": "На пляжах, на полях, в воздухе — везде бьёт.", "cooldown": 3},
        ],
    },
    {
        "id": "stalin",
        "name": "Иосиф Стулин",
        "name_en": "Joseph Stulin",
        "country": "🇷🇺",
        "era": "historical",
        "type": "Контроль",
        "bio": "Стальной человек. Построил сверхдержаву. Ценой...",
        "taunt": "Одна смерть — трагедия. Миллион — статистика.",
        "hp": 260, "atk": 32, "def": 30, "spd": 4, "luck": 5,
        "weakness": "Паранойя",
        "strength": "Массовая мобилизация",
        "strength_meme": "Приказал — миллион встал. Буквально 🔴",
        "weakness_meme": "Параноит от собственной тени 👥",
        "color": "#922b21",
        "gradient": "linear-gradient(135deg, #641e16, #922b21, #c0392b)",
        "emoji": "⭐",
        "moves": [
            {"name": "Усатый взгляд", "type": "light", "base_dmg": 14, "accuracy": 90, "desc": "Один взгляд из-под усов — и все замолчали. Навсегда."},
            {"name": "Нет человека", "type": "heavy", "base_dmg": 35, "accuracy": 58, "desc": "Вычёркивает врага из фотографии. Враг исчезает."},
            {"name": "Трубка мудрости", "type": "special", "base_dmg": 24, "accuracy": 74, "desc": "Раскуривает трубку. Дым формирует ГУЛАГ вокруг врага.", "effect": "def_down"},
            {"name": "Катюша-шторм", "type": "ultimate", "base_dmg": 56, "accuracy": 62, "desc": "Тысячи «Катюш». Земля дрожит. Песня играет.", "cooldown": 3},
        ],
    },
    {
        "id": "napoleon",
        "name": "Наполеон Бонопарт",
        "name_en": "Napoleon Bonopart",
        "country": "🇫🇷",
        "era": "historical",
        "type": "Ассасин",
        "bio": "Маленький, но великий. Покорил Европу за 10 лет.",
        "taunt": "Impossible n'est pas français!",
        "hp": 200, "atk": 40, "def": 20, "spd": 9, "luck": 7,
        "weakness": "Зима",
        "strength": "Тактика",
        "strength_meme": "Тактический гений ростом 170 📏🧠",
        "weakness_meme": "Зима: 0 — Наполеон: минус армия ❄️☠️",
        "color": "#2e4057",
        "gradient": "linear-gradient(135deg, #1b2631, #2e4057, #85929e)",
        "emoji": "👑",
        "moves": [
            {"name": "Рука в жилете", "type": "light", "base_dmg": 16, "accuracy": 88, "desc": "Что он там прячет? Нож? Пирожок? Комплекс?"},
            {"name": "Комплекс Наполеона", "type": "heavy", "base_dmg": 34, "accuracy": 58, "desc": "168 см ярости. Бьёт снизу вверх. Больнее чем сверху."},
            {"name": "Аустерлиц", "type": "special", "base_dmg": 26, "accuracy": 72, "desc": "Гениальный манёвр. Враг думал что победил. Нет.", "effect": "spd_up"},
            {"name": "Grande Armée", "type": "ultimate", "base_dmg": 55, "accuracy": 60, "desc": "600к солдат идут. Только не в Россию. НЕ В РОССИЮ!", "cooldown": 3},
        ],
    },
    {
        "id": "lincoln",
        "name": "Авраам Линколен",
        "name_en": "Abraham Lincolen",
        "country": "🇺🇸",
        "era": "historical",
        "type": "Бруйзер",
        "bio": "2 метра роста. Боролся за свободу. И просто боролся.",
        "taunt": "Четыре счёта и семь лет назад...",
        "hp": 250, "atk": 30, "def": 26, "spd": 5, "luck": 7,
        "weakness": "Театры",
        "strength": "Справедливость",
        "strength_meme": "Справедливость — его суперсила 🦸",
        "weakness_meme": "НИКОГДА не садись в первый ряд 🎭💀",
        "color": "#2c3e50",
        "gradient": "linear-gradient(135deg, #1c2833, #2c3e50, #566573)",
        "emoji": "🎭",
        "moves": [
            {"name": "Борода-щит", "type": "light", "base_dmg": 14, "accuracy": 88, "desc": "Борода такая густая, что отражает удары. И пули. Почти."},
            {"name": "Рельсоразделитель", "type": "heavy", "base_dmg": 32, "accuracy": 60, "desc": "205 см роста. Колет дрова. Дрова — это враг."},
            {"name": "Реслинг президента", "type": "special", "base_dmg": 22, "accuracy": 76, "desc": "Да, он реально был рестлером. 300 боёв. 1 поражение.", "effect": "atk_up"},
            {"name": "Ложа №5 (реванш)", "type": "ultimate", "base_dmg": 48, "accuracy": 70, "desc": "На этот раз оборачивается ПЕРВЫМ. Враг не ожидал.", "cooldown": 3},
        ],
    },
    {
        "id": "jfk",
        "name": "Джон Кеннеби",
        "name_en": "John F. Kennebi",
        "country": "🇺🇸",
        "era": "historical",
        "type": "Саппорт",
        "bio": "Молодой, красивый, смелый. Карибский кризис — его бой.",
        "taunt": "Не спрашивай, что страна может сделать для тебя.",
        "hp": 210, "atk": 28, "def": 22, "spd": 7, "luck": 4,
        "weakness": "Открытые кабриолеты",
        "strength": "Дипломатия",
        "strength_meme": "Дипломатия уровня чит-код 🗝️",
        "weakness_meme": "Открытые машины... не его вещь 🚗💨",
        "color": "#2874a6",
        "gradient": "linear-gradient(135deg, #1b4f72, #2874a6, #aed6f1)",
        "emoji": "🌊",
        "moves": [
            {"name": "Я — берлинский пончик", "type": "light", "base_dmg": 14, "accuracy": 86, "desc": "Кидает гигантский берлинер в лицо. Ich bin ein Donut!"},
            {"name": "Карибский кризис", "type": "heavy", "base_dmg": 32, "accuracy": 60, "desc": "Блокада. Мир на грани. Враг тоже на грани."},
            {"name": "Лунная гонка", "type": "special", "base_dmg": 20, "accuracy": 80, "desc": "Запускает врага на Луну. В одну сторону.", "effect": "spd_down"},
            {"name": "Кабриолет-реванш", "type": "ultimate", "base_dmg": 46, "accuracy": 72, "desc": "На этот раз крыша закрыта. И пулемёт сверху.", "cooldown": 3},
        ],
    },
    {
        "id": "castro",
        "name": "Фидель Кустро",
        "name_en": "Fidel Kustro",
        "country": "🇨🇺",
        "era": "historical",
        "type": "Танк",
        "bio": "638 покушений. Ноль результата. Команданте бессмертен.",
        "taunt": "¡Patria o muerte!",
        "hp": 290, "atk": 24, "def": 30, "spd": 4, "luck": 10,
        "weakness": "Экономика",
        "strength": "Выживание",
        "strength_meme": "638 покушений. Жив. Легенда 🐱‍👤",
        "weakness_meme": "Экономика? Слышал, не пробовал 🤷‍♂️",
        "color": "#196f3d",
        "gradient": "linear-gradient(135deg, #0b5345, #196f3d, #82e0aa)",
        "emoji": "🧔",
        "moves": [
            {"name": "Взрывающаяся сигара", "type": "light", "base_dmg": 11, "accuracy": 90, "desc": "ЦРУ подложило сигару. Кастро выкурил. ЦРУ взорвалось."},
            {"name": "638 попыток", "type": "heavy", "base_dmg": 30, "accuracy": 62, "desc": "638 покушений. Ноль результата. Этот мужик бессмертен."},
            {"name": "Молочная одержимость", "type": "special", "base_dmg": 16, "accuracy": 85, "desc": "Кастро обожал молоко. Топит врага в молочной реке.", "effect": "hp_regen"},
            {"name": "Бессмертный команданте", "type": "ultimate", "base_dmg": 48, "accuracy": 68, "desc": "Невозможно убить. ЦРУ подтверждает. 638 раз.", "cooldown": 3},
        ],
    },
    {
        "id": "thatcher",
        "name": "Маргарет Тэпчер",
        "name_en": "Margaret Thepcher",
        "country": "🇬🇧",
        "era": "historical",
        "type": "Контроль",
        "bio": "Железная леди. Ломает профсоюзы, нации и оппонентов.",
        "taunt": "The lady is not for turning!",
        "hp": 230, "atk": 30, "def": 28, "spd": 5, "luck": 6,
        "weakness": "Шахтёры",
        "strength": "Железная воля",
        "strength_meme": "Железная леди ломает всё кроме себя 🔩",
        "weakness_meme": "Шахтёры — её кошмар каждую ночь ⛏️😱",
        "color": "#1f618d",
        "gradient": "linear-gradient(135deg, #154360, #1f618d, #85c1e9)",
        "emoji": "🫖",
        "moves": [
            {"name": "Удар сумочкой", "type": "light", "base_dmg": 14, "accuracy": 90, "desc": "Legendary Thatcher Handbag. +50 к урону за каждый профсоюз."},
            {"name": "Milk Snatcher", "type": "heavy", "base_dmg": 34, "accuracy": 58, "desc": "Отбирает молоко. У школьников. У врага. У всех."},
            {"name": "Приватизация", "type": "special", "base_dmg": 22, "accuracy": 76, "desc": "Скупает ресурсы врага. Теперь его оружие — её оружие.", "effect": "atk_down"},
            {"name": "Not For Turning", "type": "ultimate", "base_dmg": 50, "accuracy": 66, "desc": "Не поворачивает. Не останавливается. Не жалеет.", "cooldown": 3},
        ],
    },
    {
        "id": "mao",
        "name": "Мяо Цзэдун",
        "name_en": "Myao Zedong",
        "country": "🇨🇳",
        "era": "historical",
        "type": "Контроль",
        "bio": "Великий кормчий. Море людей — его оружие.",
        "taunt": "Политическая власть растёт из дула винтовки.",
        "hp": 260, "atk": 28, "def": 28, "spd": 3, "luck": 6,
        "weakness": "Птицы",
        "strength": "Массы",
        "strength_meme": "Миллиард людей делают что скажет 🏮",
        "weakness_meme": "Воробьи отомстили. Природа: 1-0 🐦",
        "color": "#c0392b",
        "gradient": "linear-gradient(135deg, #78281f, #c0392b, #f1948a)",
        "emoji": "📕",
        "moves": [
            {"name": "Красная книжечка", "type": "light", "base_dmg": 13, "accuracy": 90, "desc": "Кидает цитатник. 6 миллиардов копий — хватит на всех."},
            {"name": "Война воробьям", "type": "heavy", "base_dmg": 30, "accuracy": 60, "desc": "Убил всех воробьёв → жуки сожрали урожай → голод. Гений."},
            {"name": "Священный манго", "type": "special", "base_dmg": 24, "accuracy": 72, "desc": "Дарит манго. Враг поклоняется ему как святыне (реальный факт).", "effect": "confuse"},
            {"name": "Заплыв в Янцзы", "type": "ultimate", "base_dmg": 52, "accuracy": 64, "desc": "72 года, плывёт через Янцзы. Топит всех на пути.", "cooldown": 3},
        ],
    },
    {
        "id": "caesar",
        "name": "Юлий Цузарь",
        "name_en": "Julius Cuzar",
        "country": "🇮🇹",
        "era": "historical",
        "type": "Ассасин",
        "bio": "Пришёл. Увидел. Победил. Потом зарезали.",
        "taunt": "Veni, vidi, vici!",
        "hp": 200, "atk": 38, "def": 20, "spd": 8, "luck": 3,
        "weakness": "Друзья с ножами",
        "strength": "Харизма полководца",
        "strength_meme": "Ave Caesar! Харизма на максимуме 🏛️👑",
        "weakness_meme": "Лучший друг с ножом? Норма 🗡️😊",
        "color": "#7d6608",
        "gradient": "linear-gradient(135deg, #7d6608, #d4ac0d, #f9e79f)",
        "emoji": "🏛️",
        "moves": [
            {"name": "Салатная бомба", "type": "light", "base_dmg": 16, "accuracy": 88, "desc": "Салат «Цезарь» в лицо. Назван не в его честь, но пофиг."},
            {"name": "Et tu, Brute?", "type": "heavy", "base_dmg": 34, "accuracy": 60, "desc": "23 удара. От друзей. Но Цезарь встаёт и бьёт в ответ."},
            {"name": "Лысый и злой", "type": "special", "base_dmg": 24, "accuracy": 74, "desc": "Комплексовал из-за лысины. Лавровый венок = шлем ярости.", "effect": "atk_up"},
            {"name": "Alea iacta est", "type": "ultimate", "base_dmg": 54, "accuracy": 62, "desc": "Жребий брошен. Рубикон перейдён. Салат подан.", "cooldown": 3},
        ],
    },
    {
        "id": "cleopatra",
        "name": "Клеопутра",
        "name_en": "Cleoputra",
        "country": "🇪🇬",
        "era": "historical",
        "type": "Ассасин",
        "bio": "Последняя фараон. Обольстила Рим. Яд — её выбор.",
        "taunt": "Египет не склоняется.",
        "hp": 180, "atk": 36, "def": 16, "spd": 9, "luck": 9,
        "weakness": "Открытый бой",
        "strength": "Интриги",
        "strength_meme": "Интриги уровня Netflix-сериал 🐍👑",
        "weakness_meme": "Фейс-ту-фейс? Нет, спасибо 🙅‍♀️",
        "color": "#d4ac0d",
        "gradient": "linear-gradient(135deg, #7d6608, #d4ac0d, #f4d03f)",
        "emoji": "🐍",
        "moves": [
            {"name": "Молочная ванна", "type": "light", "base_dmg": 15, "accuracy": 92, "desc": "Топит врага в ванне с ослиным молоком. Кожа потом супер."},
            {"name": "Доставка в ковре", "type": "heavy", "base_dmg": 30, "accuracy": 58, "desc": "Выкатывается из ковра и бьёт. Как к Цезарю, только больнее."},
            {"name": "Обольщение", "type": "special", "base_dmg": 22, "accuracy": 80, "desc": "Соблазнила 2 империи. Враг теряет волю.", "effect": "confuse"},
            {"name": "Проклятие фараонов", "type": "ultimate", "base_dmg": 52, "accuracy": 66, "desc": "Аспид + мумии + проклятие. Египетский комбо.", "cooldown": 3},
        ],
    },
    {
        "id": "genghis",
        "name": "Чингисхен",
        "name_en": "Genghis Khen",
        "country": "🇲🇳",
        "era": "historical",
        "type": "Бруйзер",
        "bio": "Покорил полмира на лошади. 0.5% мужчин — его потомки.",
        "taunt": "Покорись или умри.",
        "hp": 250, "atk": 42, "def": 22, "spd": 8, "luck": 7,
        "weakness": "Осады",
        "strength": "Конная мощь",
        "strength_meme": "Конница из ада. Земля дрожит 🐴🔥",
        "weakness_meme": "Осады? Подождём. Год-два 🏰⏳",
        "color": "#6c3461",
        "gradient": "linear-gradient(135deg, #4a235a, #6c3461, #a569bd)",
        "emoji": "🏹",
        "moves": [
            {"name": "Кумыс в лицо", "type": "light", "base_dmg": 16, "accuracy": 88, "desc": "Кобылье молоко, забродившее. В глаза. Жжёт."},
            {"name": "Гора черепов", "type": "heavy", "base_dmg": 36, "accuracy": 58, "desc": "Строит пирамиду из черепов. Из вражеских."},
            {"name": "0.5% твой папа", "type": "special", "base_dmg": 24, "accuracy": 76, "desc": "0.5% мужчин — его потомки. Враг, возможно, тоже.", "effect": "confuse"},
            {"name": "Орда", "type": "ultimate", "base_dmg": 58, "accuracy": 60, "desc": "Вся Великая Степь обрушивается. Земля дрожит.", "cooldown": 3},
        ],
    },
    {
        "id": "che",
        "name": "Че Гивара",
        "name_en": "Che Givara",
        "country": "🇨🇺",
        "era": "historical",
        "type": "Бруйзер",
        "bio": "Революционный романтик. Борода, берет, партизанская война.",
        "taunt": "Hasta la victoria siempre!",
        "hp": 210, "atk": 34, "def": 20, "spd": 7, "luck": 6,
        "weakness": "Логистика",
        "strength": "Партизанство",
        "strength_meme": "Партизан #1. Джунгли — его дом 🌿",
        "weakness_meme": "Логистика? Что это за покемон? 📦❓",
        "color": "#27ae60",
        "gradient": "linear-gradient(135deg, #1e8449, #27ae60, #82e0aa)",
        "emoji": "⭐",
        "moves": [
            {"name": "Ирония мерча", "type": "light", "base_dmg": 15, "accuracy": 88, "desc": "Бьёт футболкой со своим лицом. $29.99 на Amazon."},
            {"name": "Мотоцикл!", "type": "heavy", "base_dmg": 32, "accuracy": 60, "desc": "Norton 500 проносится мимо. Удар сбоку на полном ходу."},
            {"name": "Берет-сюрикен", "type": "special", "base_dmg": 22, "accuracy": 76, "desc": "Снимает берет — внутри звезда. Кидает как сюрикен.", "effect": "spd_up"},
            {"name": "Revolución Total", "type": "ultimate", "base_dmg": 50, "accuracy": 64, "desc": "Латинская Америка восстаёт. Футболки продаются.", "cooldown": 3},
        ],
    },
    {
        "id": "obama",
        "name": "Барак Обума",
        "name_en": "Barack Obuma",
        "country": "🇺🇸",
        "era": "current",
        "type": "Саппорт",
        "bio": "44-й президент. Элегантный оратор. Yes we can.",
        "taunt": "Yes we can!",
        "hp": 220, "atk": 26, "def": 26, "spd": 7, "luck": 8,
        "weakness": "Нерешительность",
        "strength": "Красноречие",
        "strength_meme": "Yes we can заставляет плакать 🎤😢",
        "weakness_meme": "Думает слишком долго. Мемы ждут 🤔⏰",
        "color": "#2e86c1",
        "gradient": "linear-gradient(135deg, #1b4f72, #2e86c1, #aed6f1)",
        "emoji": "🎤",
        "moves": [
            {"name": "Thanks Obama", "type": "light", "base_dmg": 12, "accuracy": 92, "desc": "Мем стал реальностью. Всё плохое — вина врага."},
            {"name": "Бежевый костюм", "type": "heavy", "base_dmg": 35, "accuracy": 60, "desc": "Надел БЕЖЕВЫЙ костюм. Fox News взорвался. Враг тоже."},
            {"name": "Mic Drop", "type": "special", "base_dmg": 16, "accuracy": 85, "desc": "Бросает микрофон. Попадает. Obama out.", "effect": "def_down"},
            {"name": "Yes We Can (финишер)", "type": "ultimate", "base_dmg": 46, "accuracy": 72, "desc": "Весь зал скандирует. Звуковая волна. Враг плачет.", "cooldown": 3},
        ],
    },
    # ───────────── ADDED ─────────────
    {
        "id": "peter_i",
        "name": "Пётр Й",
        "name_en": "Peter the Greet",
        "country": "🇷🇺",
        "era": "historical",
        "type": "Берсерк",
        "bio": "Два метра ярости и реформ. Построил город на костях и стал Великим.",
        "taunt": "Рубить бороды!",
        "hp": 260, "atk": 40, "def": 22, "spd": 5, "luck": 7,
        "weakness": "Терпение",
        "strength": "Грубая сила",
        "strength_meme": "Бьёт грубо. Строит круто 🔨🏗️",
        "weakness_meme": "Терпение? Не слышал. Где топор? 🪓",
        "color": "#1565c0",
        "gradient": "linear-gradient(135deg, #0d47a1, #1565c0, #42a5f5)",
        "emoji": "⚓",
        "moves": [
            {"name": "Ножницы для бороды", "type": "light", "base_dmg": 15, "accuracy": 88, "desc": "Стрижёт бороду врага. Без бороды −50 к мужественности."},
            {"name": "204 см ярости", "type": "heavy", "base_dmg": 36, "accuracy": 56, "desc": "Два метра четыре. Размахивает боярином как дубиной."},
            {"name": "Построил город на болоте", "type": "special", "base_dmg": 20, "accuracy": 76, "desc": "Врага засасывает болото. Сверху строится Петербург.", "effect": "spd_down"},
            {"name": "Великое посольство", "type": "ultimate", "base_dmg": 52, "accuracy": 66, "desc": "Уехал в Европу плотником, вернулся с флотом и пушками", "cooldown": 3},
        ],
    },
    {
        "id": "gorbachev",
        "name": "Михаил Горбочёв",
        "name_en": "Mikhail Gorbochev",
        "country": "🇷🇺",
        "era": "historical",
        "type": "Саппорт",
        "bio": "Развалил сверхдержаву, получил Нобелевскую. Рекламировал пиццу.",
        "taunt": "Гласность и перестройка!",
        "hp": 200, "atk": 15, "def": 28, "spd": 4, "luck": 6,
        "weakness": "Решительность",
        "strength": "Дипломатия",
        "strength_meme": "Дипломатия 100. Навык разблокирован 🕊️",
        "weakness_meme": "Решительность на минималках 📉",
        "color": "#7b1fa2",
        "gradient": "linear-gradient(135deg, #4a148c, #7b1fa2, #ce93d8)",
        "emoji": "☮️",
        "moves": [
            {"name": "Пицца Хат слэм", "type": "light", "base_dmg": 10, "accuracy": 92, "desc": "Кидает пиццу. Как в рекламе, только в лицо."},
            {"name": "Пятно на лбу", "type": "heavy", "base_dmg": 26, "accuracy": 65, "desc": "Родимое пятно гипнотизирует. Враг не может отвести глаз."},
            {"name": "Процесс пошёл", "type": "special", "base_dmg": 16, "accuracy": 80, "desc": "Начинает процесс. Останавливать поздно. Всё рушится.", "effect": "confuse"},
            {"name": "Случайный развал", "type": "ultimate", "base_dmg": 60, "accuracy": 50, "desc": "15 республик разлетаются. Случайно. Упс.", "cooldown": 3},
        ],
    },
    {
        "id": "yeltsin",
        "name": "Борис Ёлцин",
        "name_en": "Boris Yolcin",
        "country": "🇷🇺",
        "era": "historical",
        "type": "Берсерк",
        "bio": "Встал на танк и стал президентом. Дирижировал оркестром в Берлине.",
        "taunt": "Я устал, я ухожу.",
        "hp": 230, "atk": 35, "def": 16, "spd": 3, "luck": 9,
        "weakness": "Координация",
        "strength": "Непредсказуемость",
        "strength_meme": "Непредсказуем как русская рулетка 🎰",
        "weakness_meme": "Координация... после третьей 🍷🌀",
        "color": "#e65100",
        "gradient": "linear-gradient(135deg, #bf360c, #e65100, #ff9800)",
        "emoji": "🍾",
        "moves": [
            {"name": "Пьяный дирижёр", "type": "light", "base_dmg": 12, "accuracy": 85, "desc": "Дирижирует оркестром в Берлине. Палочка попадает в глаз."},
            {"name": "Танцы-выборы", "type": "heavy", "base_dmg": 33, "accuracy": 60, "desc": "Танцует на сцене. Так энергично, что сцена рушится на врага."},
            {"name": "Стоя на танке", "type": "special", "base_dmg": 18, "accuracy": 72, "desc": "Залезает на танк. Харизма 100. Танк едет на врага.", "effect": "atk_up"},
            {"name": "Я устал, я ухожу", "type": "ultimate", "base_dmg": 48, "accuracy": 70, "desc": "Уходит. Но шоковая волна от ухода — ядерная.", "cooldown": 3},
        ],
    },
    {
        "id": "catherine_ii",
        "name": "Екотерина II",
        "name_en": "Catharine the Great",
        "country": "🇷🇺",
        "era": "historical",
        "type": "Контроль",
        "bio": "Немка на русском троне. Расширила империю больше, чем любой царь.",
        "taunt": "Просвещение — мой клинок.",
        "hp": 240, "atk": 26, "def": 30, "spd": 5, "luck": 8,
        "weakness": "Доверие к фаворитам",
        "strength": "Интриги",
        "strength_meme": "Интриги? Это моё второе имя 👸🕸️",
        "weakness_meme": "Фавориты — слабое место 💕👀",
        "color": "#ab47bc",
        "gradient": "linear-gradient(135deg, #6a1b9a, #ab47bc, #f48fb1)",
        "emoji": "👑",
        "moves": [
            {"name": "Указ Императрицы", "type": "light", "base_dmg": 12, "accuracy": 90, "desc": "Подписывает указ. «Казнить» — без второй части предложения."},
            {"name": "ТОТ САМЫЙ конь", "type": "heavy", "base_dmg": 30, "accuracy": 62, "desc": "Конь. Бронзовый. С Медного всадника. Прямо в лоб."},
            {"name": "21 фаворит", "type": "special", "base_dmg": 22, "accuracy": 78, "desc": "Все 21 фаворит атакуют одновременно. Очередь.", "effect": "atk_down"},
            {"name": "Золотой век", "type": "ultimate", "base_dmg": 50, "accuracy": 66, "desc": "Расцвет империи. Закат для врагов. Корона сияет.", "cooldown": 3},
        ],
    },
    {
        "id": "ivan_terrible",
        "name": "Иван Грузный",
        "name_en": "Ivan the Terribel",
        "country": "🇷🇺",
        "era": "historical",
        "type": "Берсерк",
        "bio": "Первый русский царь. Опричнина, паранойя и метание посохов.",
        "taunt": "Казнить нельзя помиловать.",
        "hp": 250, "atk": 42, "def": 20, "spd": 4, "luck": 5,
        "weakness": "Паранойя",
        "strength": "Страх",
        "strength_meme": "Один взгляд — и все молчат 👁️💀",
        "weakness_meme": "Параноик уровня: убил своего сына 😬",
        "color": "#880e4f",
        "gradient": "linear-gradient(135deg, #4a0028, #880e4f, #c62828)",
        "emoji": "🪓",
        "moves": [
            {"name": "Посох. ТОТ САМЫЙ.", "type": "light", "base_dmg": 16, "accuracy": 84, "desc": "Железный посох. Да, тот самый. Не уклонишься."},
            {"name": "Картина Репина", "type": "heavy", "base_dmg": 38, "accuracy": 55, "desc": "Картина оживает. Враг не успевает крикнуть «папа»."},
            {"name": "Опричнина", "type": "special", "base_dmg": 24, "accuracy": 72, "desc": "Псоглавцы с мётлами. Выметают всё. И всех.", "effect": "def_down"},
            {"name": "Гнев Царя", "type": "ultimate", "base_dmg": 58, "accuracy": 58, "desc": "Приступ ярости. Ломает всё в радиусе. Включая семью.", "cooldown": 3},
        ],
    },
    {
        "id": "yushchenko",
        "name": "Виктор Ющёнко",
        "name_en": "Viktor Yushchonko",
        "country": "🇺🇦",
        "era": "current",
        "type": "Танк",
        "bio": "3-й президент Украины. Оранжевая революция и лицо, которое не забудешь.",
        "taunt": "Так!",
        "hp": 240, "atk": 20, "def": 30, "spd": 4, "luck": 6,
        "weakness": "Популярность",
        "strength": "Стойкость",
        "strength_meme": "Выжил после отравления. Реально 💪☠️",
        "weakness_meme": "Популярность? Была... когда-то 📉",
        "color": "#ff6f00",
        "gradient": "linear-gradient(135deg, #e65100, #ff6f00, #ffa726)",
        "emoji": "🍯",
        "moves": [
            {"name": "Пчёлы с пасеки!", "type": "light", "base_dmg": 11, "accuracy": 90, "desc": "Рой пчёл. С ЛИЧНОЙ пасеки. Органический урон."},
            {"name": "Оранжевая волна", "type": "heavy", "base_dmg": 30, "accuracy": 60, "desc": "Майдан-2004. Оранжевое цунами сметает врага."},
            {"name": "Диоксин-реверс", "type": "special", "base_dmg": 20, "accuracy": 75, "desc": "Отравили его — теперь он травит. Справедливость.", "effect": "def_down"},
            {"name": "ТАК! ТАК! ТАК!", "type": "ultimate", "base_dmg": 46, "accuracy": 68, "desc": "Звуковая волна из одного слова. ТАК! Стены трещат.", "cooldown": 3},
        ],
    },
    {
        "id": "kuchma",
        "name": "Леонид Кочма",
        "name_en": "Leonid Kochma",
        "country": "🇺🇦",
        "era": "current",
        "type": "Контроль",
        "bio": "2-й президент Украины. Ракетчик, прагматик, мастер многовекторности.",
        "taunt": "Украина — не Россия.",
        "hp": 230, "atk": 22, "def": 28, "spd": 4, "luck": 5,
        "weakness": "Скандалы",
        "strength": "Многовекторность",
        "strength_meme": "Многовекторность — его суперсила 🧭",
        "weakness_meme": "Плёнки Мельниченко. Ой 🎙️😰",
        "color": "#546e7a",
        "gradient": "linear-gradient(135deg, #37474f, #546e7a, #90a4ae)",
        "emoji": "🚀",
        "moves": [
            {"name": "Многовекторный удар", "type": "light", "base_dmg": 12, "accuracy": 88, "desc": "Бьёт со всех направлений сразу. Восток, Запад, и по диагонали."},
            {"name": "Сатана (Р-36М)", "type": "heavy", "base_dmg": 36, "accuracy": 52, "desc": "Ракета из Южмаша. Куда полетит — даже инженер не знает."},
            {"name": "Кассетный скандал", "type": "special", "base_dmg": 16, "accuracy": 82, "desc": "Диктофон записал ВСЁ. Включая секреты врага.", "effect": "def_down"},
            {"name": "Книга-тектоника", "type": "ultimate", "base_dmg": 48, "accuracy": 65, "desc": "«Украина — не Россия» материализуется и раскалывает землю", "cooldown": 3},
        ],
    },
    {
        "id": "zhirinovsky",
        "name": "Владимир Жириновскей",
        "name_en": "Vladimir Zhirinovskei",
        "country": "🇷🇺",
        "era": "historical",
        "type": "Берсерк",
        "bio": "Главный политический шоумен и мастер орать громче всех в студии.",
        "taunt": "Я вам покажу кузькину мать в прямом эфире!",
        "hp": 235, "atk": 34, "def": 20, "spd": 5, "luck": 7,
        "weakness": "Самоконтроль",
        "strength": "Скандалы",
        "strength_meme": "СКАНДАЛ! СКАНДАЛ! РЕЙТИНГИ ЛЕТЯТ! 📺🚀",
        "weakness_meme": "Самоконтроль? Нет, не слышал 🤬",
        "color": "#283593",
        "gradient": "linear-gradient(135deg, #1a237e, #283593, #7986cb)",
        "emoji": "🗣️",
        "moves": [
            {"name": "Стакан воды", "type": "light", "base_dmg": 14, "accuracy": 90, "desc": "Плескает водой в оппонента прямо в эфире. Классика жанра."},
            {"name": "Ору на всю студию", "type": "heavy", "base_dmg": 34, "accuracy": 58, "desc": "Крик такой силы, что микрофоны хрипят, а враг теряет ориентацию."},
            {"name": "Пламенный спич", "type": "special", "base_dmg": 20, "accuracy": 78, "desc": "Толкает речь на десять минут без вдоха. Враг сдаётся морально.", "effect": "atk_down"},
            {"name": "Эфирный апокалипсис", "type": "ultimate", "base_dmg": 52, "accuracy": 64, "desc": "Ток-шоу превращается в конец света. Все орут, враг падает первым.", "cooldown": 3},
        ],
    },
    {
        "id": "reagan",
        "name": "Рональд Рёйган",
        "name_en": "Ronald Reygan",
        "country": "🇺🇸",
        "era": "historical",
        "type": "Бруйзер",
        "bio": "Голливудский актёр ставший президентом. Развалил СССР улыбкой и СОИ.",
        "taunt": "Mr. Gorbachev, tear down this wall!",
        "hp": 235, "atk": 30, "def": 25, "spd": 5, "luck": 8,
        "weakness": "Возраст",
        "strength": "Харизма",
        "strength_meme": "Голливуд + Белый дом = харизма x999 🎬",
        "weakness_meme": "Возраст — не число, а дебафф 👴",
        "color": "#1565c0",
        "gradient": "linear-gradient(135deg, #0d47a1, #1565c0, #ef5350)",
        "emoji": "🎬",
        "moves": [
            {"name": "Голливудский хук", "type": "light", "base_dmg": 13, "accuracy": 90, "desc": "Улыбка актёра — а потом кулак президента. Сюрприз."},
            {"name": "Засыпает → просыпается", "type": "heavy", "base_dmg": 34, "accuracy": 58, "desc": "Заснул на совещании. Проснулся Терминатором."},
            {"name": "Мармеладки (SDI)", "type": "special", "base_dmg": 22, "accuracy": 74, "desc": "Jelly beans из космоса. Может блеф. А может нет.", "effect": "atk_down"},
            {"name": "Tear Down This Wall", "type": "ultimate", "base_dmg": 52, "accuracy": 65, "desc": "Стена рухнула. За ней — весь Восточный блок. И счёт.", "cooldown": 3},
        ],
    },
    {
        "id": "alexander_great",
        "name": "Александр Макидонский",
        "name_en": "Alexunder the Great",
        "country": "🇬🇷",
        "era": "historical",
        "type": "Берсерк",
        "bio": "Завоевал полмира к 30 годам. Умер непобеждённым в 32.",
        "taunt": "Мир слишком мал для меня.",
        "hp": 250, "atk": 42, "def": 22, "spd": 8, "luck": 9,
        "weakness": "Самоуверенность",
        "strength": "Тактика",
        "strength_meme": "В 30 лет завоевал полмира. А ты? 🌍",
        "weakness_meme": "Думает что непобедим. Спойлер: нет 💀",
        "color": "#ffd600",
        "gradient": "linear-gradient(135deg, #f9a825, #ffd600, #fff9c4)",
        "emoji": "⚔️",
        "moves": [
            {"name": "Александрия №47", "type": "light", "base_dmg": 14, "accuracy": 90, "desc": "Называет ОЧЕРЕДНОЙ город в свою честь. На месте врага."},
            {"name": "Разруб Гордиева узла", "type": "heavy", "base_dmg": 36, "accuracy": 58, "desc": "Не развязал? Разрубил. Не решил? Разрубил. Всё разрубил."},
            {"name": "Спидран", "type": "special", "base_dmg": 24, "accuracy": 75, "desc": "Завоевал мир за 13 лет. Any% WR. Враг не успевает.", "effect": "spd_up"},
            {"name": "Вечеринка в Вавилоне", "type": "ultimate", "base_dmg": 56, "accuracy": 62, "desc": "Гулял 10 дней. Умер. Но перед этим уничтожил всё.", "cooldown": 3},
        ],
    },
    {
        "id": "mandela",
        "name": "Нельсон Мондела",
        "name_en": "Nelson Mondela",
        "country": "🇿🇦",
        "era": "historical",
        "type": "Танк",
        "bio": "27 лет в тюрьме. Вышел и стал президентом. Символ несломленной воли.",
        "taunt": "Я — хозяин своей судьбы.",
        "hp": 280, "atk": 18, "def": 36, "spd": 3, "luck": 8,
        "weakness": "Скорость",
        "strength": "Несломимость",
        "strength_meme": "27 лет в тюрьме → президент. GG 🏆",
        "weakness_meme": "Медленный как мудрость 🐢🧠",
        "color": "#2e7d32",
        "gradient": "linear-gradient(135deg, #1b5e20, #2e7d32, #fdd835)",
        "emoji": "✊🏿",
        "moves": [
            {"name": "27 лет терпения", "type": "light", "base_dmg": 10, "accuracy": 94, "desc": "Каждый год в тюрьме — отдельный удар. 27 штук."},
            {"name": "Эффект Манделы", "type": "heavy", "base_dmg": 30, "accuracy": 62, "desc": "Враг помнит, что уже победил. Но нет. Ложная память."},
            {"name": "Прощение", "type": "special", "base_dmg": 16, "accuracy": 82, "desc": "Прощает врага. Врагу так стыдно, что теряет волю к бою.", "effect": "atk_down"},
            {"name": "Rainbow Nation", "type": "ultimate", "base_dmg": 48, "accuracy": 70, "desc": "Целая нация за спиной. Радуга бьёт как молот.", "cooldown": 3},
        ],
    },
    {
        "id": "roosevelt",
        "name": "Франклин Розвельт",
        "name_en": "Franklin D. Rosevelt",
        "country": "🇺🇸",
        "era": "historical",
        "type": "Контроль",
        "bio": "4 срока, Новый курс, и победа во Второй мировой. Управлял из кресла.",
        "taunt": "Нам нечего бояться, кроме самого страха.",
        "hp": 260, "atk": 24, "def": 32, "spd": 2, "luck": 7,
        "weakness": "Мобильность",
        "strength": "Стратегия",
        "strength_meme": "Стратег из коляски. Топ-1 🧠♿",
        "weakness_meme": "Мобильность: вы серьёзно? 🦽",
        "color": "#1a237e",
        "gradient": "linear-gradient(135deg, #0d1452, #1a237e, #42a5f5)",
        "emoji": "🦅",
        "moves": [
            {"name": "Коляской по ноге", "type": "light", "base_dmg": 12, "accuracy": 90, "desc": "Инвалидная коляска. Переезжает по пальцам. Больно."},
            {"name": "Ленд-лиз", "type": "heavy", "base_dmg": 32, "accuracy": 60, "desc": "Бесконечные поставки оружия. Конвейер урона."},
            {"name": "Fireside Chat", "type": "special", "base_dmg": 18, "accuracy": 80, "desc": "Голос из радио. Гипноз. Враг садится и слушает.", "effect": "confuse"},
            {"name": "4 срока подряд", "type": "ultimate", "base_dmg": 54, "accuracy": 64, "desc": "Бьёт 4 раза. Потому что может. Конституцию поменяли потом.", "cooldown": 3},
        ],
    },
    {
        "id": "tymoshenko",
        "name": "Юлия Тимашенко",
        "name_en": "Yulia Tymashenko",
        "country": "🇺🇦",
        "era": "current",
        "type": "Ассасин",
        "bio": "Газовая принцесса. Коса — оружие. Тюрьма — санаторий. Оранжевая революция — её продюсирование.",
        "taunt": "Я ще не вмерла!",
        "hp": 210, "atk": 34, "def": 20, "spd": 8, "luck": 9,
        "weakness": "Газовые контракты",
        "strength": "Коса и харизма",
        "strength_meme": "Коса — это оружие. Буквально 🌀⚔️",
        "weakness_meme": "Газовые контракты преследуют во снах 🔥💤",
        "color": "#f48fb1",
        "gradient": "linear-gradient(135deg, #e91e63, #f48fb1, #fce4ec)",
        "emoji": "💇‍♀️",
        "moves": [
            {"name": "Удар косой", "type": "light", "base_dmg": 15, "accuracy": 92, "desc": "Коса-хлыст. Фирменная укладка наносит фирменный урон."},
            {"name": "Газовая атака", "type": "heavy", "base_dmg": 34, "accuracy": 58, "desc": "Перекрывает газ. Враг мёрзнет. Цена ×10."},
            {"name": "Тюремный побег", "type": "special", "base_dmg": 22, "accuracy": 78, "desc": "Сидела в тюрьме, вышла сильнее. На инвалидной коляске. Но коляска боевая.", "effect": "spd_up"},
            {"name": "Оранжевый переворот", "type": "ultimate", "base_dmg": 50, "accuracy": 66, "desc": "Миллион людей на Майдане. Коса развевается. Правительство падает.", "cooldown": 3},
        ],
    },
    {
        "id": "hussein",
        "name": "Саддам Хусеин",
        "name_en": "Saddam Hoosein",
        "country": "🇮🇶",
        "era": "historical",
        "type": "Берсерк",
        "bio": "Диктатор Ирака. Не нашли оружие массового поражения, но нашли его в яме.",
        "taunt": "Я вернусь! ...или нет.",
        "hp": 250, "atk": 35, "def": 28, "spd": 4, "luck": 5,
        "weakness": "Подземные укрытия",
        "strength": "Страх",
        "strength_meme": "Все боялись. Вообще все. 😨👑",
        "weakness_meme": "Прятался в яме. Не помогло 🕳️☠️",
        "color": "#2c3e50",
        "gradient": "linear-gradient(135deg, #1a1a2e, #16213e, #0f3460)",
        "emoji": "🏜️",
        "moves": [
            {"name": "Химический удар", "type": "heavy", "base_dmg": 38, "accuracy": 55, "desc": "ОМП не нашли? Значит плохо искали."},
            {"name": "Золотой AK-47", "type": "light", "base_dmg": 15, "accuracy": 88, "desc": "Золотой автомат. Стильно, дорого, больно."},
            {"name": "Двойник", "type": "special", "base_dmg": 18, "accuracy": 82, "desc": "Это не я! Это мой двойник! А может и нет...", "effect": "confuse"},
            {"name": "Нефтяной пожар", "type": "ultimate", "base_dmg": 52, "accuracy": 60, "desc": "Поджигает нефтяные скважины. Всё горит. Вообще всё.", "cooldown": 3},
        ],
    },
]

# Quick lookup
FIGHTERS_BY_ID = {f["id"]: f for f in FIGHTERS}
