[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#0052f1"
backgroundColor = "#f7fbff"
secondaryBackgroundColor = "#e5eeff"
textColor = "#212121"
font = "sans serif"
